export const storeProducts = [
    {
      id: 0,
      titre: "Google Pixel",
      img: "img/product-1.png",
      prix: 706,
      marque: "google",
      tailleEcran:5.7,
      stockage:64,
      se:"Android",
      nbCouleur:1,
      couleur:["Noir"],
      ram:4,
      processeur:"Octa-core",
      quantite: 0,
      quantiteTotal: 25
    },
    {
      id: 1,
      titre: "Samsung S7",
      img: "img/product-2.png",
      prix: 600,
      marque: "SAMSUNG",
      tailleEcran:5.1,
      stockage:32,
      se:"Android",
      nbCouleur:1,
      couleur:["Doré"],
      ram:4,
      processeur:"Exynos 8890",
      quantite: 0,
      quantiteTotal: 30
    },
    {
      id: 2,
      titre: "HTC 10",
      img: "img/product-3.png",
      prix:  1050,
      marque: "htc",
      tailleEcran:5.2,
      stockage:32,
      se:"Android",
      nbCouleur:2,
      couleur:["Noir","White"],
      ram:4,
      processeur:"Snapdragon 820",
      quantite: 0,
      quantiteTotal: 10,
      img2: "img/product-4.png",
    },
    {
      id: 3,
      titre: "HTC Desire 626s",
      img: "img/product-5.png",
      prix: 200,
      marque: "htc",
      tailleEcran:5,
      stockage:4,
      se:"Android",
      nbCouleur:1,
      couleur:["Noir"],
      ram:1,
      processeur:"Snapdragon 820",
      quantite: 0,
      quantiteTotal: 30
    },
    {
      id: 4,
      titre: "Iphone 4",
      img: "img/product-6.png",
      prix: 150,
      marque: "apple",
      tailleEcran:3.5,
      stockage:32,
      se:"iOS",
      nbCouleur:1,
      couleur:["Noir"],
      ram:1,
      processeur:"Apple A4",
      quantite: 0,
      quantiteTotal: 20
    },
    {
      id: 5,
      titre: "Iphone 7",
      img: "img/product-7.png",
      prix: 2089,
      marque: "apple",
      tailleEcran:4.7,
      stockage:32,
      se:"iOS",
      nbCouleur:1,
      couleur:["Noir"],
      ram:2,
      processeur:"A10 Fusion Apple",
      quantite: 0,
      quantiteTotal: 10
    },
 /*   {
      id: 6,
      titre: "Huawei Y7a",
      img: "img/product-8.jpg",
      prix: 699,
      marque: "Huawei",
      tailleEcran:6.67,
      stockage:128,
      se:"EMUI 10.1",
      nbCouleur:1,
      couleur:["Noir"],
      RAM:4,
      processeur:"cœurs Cortex",
      quantite: 0,
      quantiteTotal: 0
    }*/
  ];